CATALOG = [
    ("STORE SUPPLIES", "Bakeshop Holding Time Log Sheet(Siopao & Pies)", "pcs"),
    ("STORE SUPPLIES", "Employee's Comfort Room Sanitation Checklist (w/ picture)", "pcs"),
    ("STORE SUPPLIES", "Daily Pest Sighting Log Sheet", "pcs"),
    ("STORE SUPPLIES", "OFF-Spec Report Form", "pcs"),
    ("STORE SUPPLIES", "Chemical Inventory Form", "pcs"),
    ("STORE SUPPLIES", "Cold Storage Equipment Temperature Monitoring Form", "pcs"),
    ("STORE SUPPLIES", "Hot Holding Equipment Temperature Monitoring Form", "pcs"),
    ("STORE SUPPLIES", "Daily Pre and Post-Operational Inspection Checklist", "pcs"),
    ("STORE SUPPLIES", "Sando Bag Texas Small", "pcs"),
    ("STORE SUPPLIES", "Sando Bag Texas Medium", "pcs"),
    ("STORE SUPPLIES", "Sando Bag Texas Large", "pcs"),
    ("STORE SUPPLIES", "Product Transfer Report", "pcs"),
    ("STORE SUPPLIES", "Spoilage Transfer Report", "pcs"),
    ("STORE SUPPLIES", "Charge Slip", "pcs"),
    ("STORE SUPPLIES", "Sales Invoice", "pcs"),
    ("STORE SUPPLIES", "Baker Order", "pcs"),
    ("STORE SUPPLIES", "Cashier's Cash Turnover", "pcs"),
    ("STORE SUPPLIES", "Request Form", "pcs"),
    ("STORE SUPPLIES", "Inventory Form", "pcs"),
    ("STORE SUPPLIES", "C.I. Summary", "pcs"),
    ("STORE SUPPLIES", "Summary of Cash Deposit", "pcs"),
    ("STORE SUPPLIES", "E.S.A.R.F.", "pcs"),
    ("STORE SUPPLIES", "Sando Bag Large Jumper", "pcs"),
    ("STORE SUPPLIES", "Sando Bag Small Jumper", "pcs"),
    ("STORE SUPPLIES", "Sando Bag Medium Jumper", "pcs"),
    ("DESK SUPPLIES", "Paper Fastener Joy Box", "box"),
    ("DESK SUPPLIES", "Staple Wire", "box"),
    ("DESK SUPPLIES", "Casio DX-120ST Calculator", "unit"),
    ("DESK SUPPLIES", "Casio Calculator mx12 Pink", "unit"),
    ("DESK SUPPLIES", "Sharpener Nataraj", "unit"),
    ("DESK SUPPLIES", "Eraser Doms", "unit"),
    ("DESK SUPPLIES", "Joy Stapler #35", "unit"),
    ("DESK SUPPLIES", "Stapler #35", "unit"),
    ("DESK SUPPLIES", "Stapler Wire #35 HBW", "box"),
    ("DESK SUPPLIES", "HBW Puncher Big", "unit"),
    ("DESK SUPPLIES", "Stampad #2 w/Ink", "unit"),
    ("DESK SUPPLIES", "Clip Board TM TCB-02 BLK", "unit"),
    ("DESK SUPPLIES", "Clip Board TM TCB-02 Blue", "unit"),
    ("DESK SUPPLIES", "Stampad #3 w/Ink", "unit"),
    ("DESK SUPPLIES", "HBW Scissors 8 1/4", "unit"),
    ("DESK SUPPLIES", "Money Detector", "unit"),
    ("DESK SUPPLIES", 'Binder Clip 1" Joy', "box"),
    ("DESK SUPPLIES", 'Binder Clip 1 5/8 Joy', "box"),
    ("DESK SUPPLIES", "Clipboard Long No Cover", "unit"),
    ("DESK SUPPLIES", "HBW Stapler #35", "unit"),
    ("DESK SUPPLIES", "HBW Stapler Wire #35", "box"),
    ("DESK SUPPLIES", "Data Filer BLK", "unit"),
    ("DESK SUPPLIES", "Data Filer Blue", "unit"),
    ("DESK SUPPLIES", "Brite Rubber Band Big", "pack"),
    ("DESK SUPPLIES", "TM Clipboard BLK Long", "unit"),
    ("DESK SUPPLIES", "Metal Clio", "box"),
    ("DESK SUPPLIES", "3 Layer Metal Tray", "unit"),
    ("DESK SUPPLIES", "Rubber Band", "pack"),
    ("DESK SUPPLIES", "Casio Calculator MH12", "unit"),
    ("DESK SUPPLIES", "Casio Calculator MZ 12", "unit"),
    ("DESK SUPPLIES", "Deli Stapler #35", "unit"),
    ("DESK SUPPLIES", "Stamp Pad w/Ink Purple #2", "unit"),
    ("DESK SUPPLIES", "Clip Board Long Adventurer", "unit"),
    ("DESK SUPPLIES", "HBW Stampad #2 w/Ink", "unit"),
    ("DESK SUPPLIES", "Joy Puncher Big", "unit"),
    ("CLEANING SUPPLIES", "Liquid Hand Soap w/ Disinfectant", "bottle"),
    ("CLEANING SUPPLIES", "Liquid Sanitizer Chlorine base (YELLOW)", "bottle"),
    ("CLEANING SUPPLIES", "All Purpose Liquid Cleaner (BLUE)", "bottle"),
    ("CLEANING SUPPLIES", "Bathroom Tissue", "roll"),
    ("CLEANING SUPPLIES", "Alcohol", "bottle"),
    ("CLEANING SUPPLIES", "Mop Head Wood", "unit"),
    ("CLEANING SUPPLIES", "Mop Head #600", "unit"),
    ("CLEANING SUPPLIES", "Zonrox / Winrox", "bottle"),
    ("CLEANING SUPPLIES", "Scotch Brite", "pack"),
    ("CLEANING SUPPLIES", "Garbage Bag XL", "roll"),
    ("CLEANING SUPPLIES", "Calypso Garbage Bag XL (10pcs/roll)", "roll"),
    ("CLEANING SUPPLIES", "Calypso Garbage Bag XL (50pcs/roll)", "roll"),
    ("CLEANING SUPPLIES", "Pet Bottles", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Scotch Tape 1/2 IN.", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Packing Tape 2X100 Clear", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "JOJO Correction Tape", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Joy Correction Tape", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Scotch Tape 1X50'", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Masking Tape 1'", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Masking Tape 2'", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Double Sided Tape 1'", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Joy Tape Dispenser No.333 Blue", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Joy Tape Dispenser No.333 Red", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Joy Tape Dispenser No.333 Green", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Double Sided Tape w/Foam", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Double Sided Tape w/Foam 1' Green", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "TM Tape Dispenser Big Black", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "TM Tape Dispenser Big Blue", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "HBW Tape Dispenser TD-2031", "unit"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "Scotch Tape 1'", "roll"),
    ("TAPE / TAPE DISPENSER / CORRECTION TAPE", "HBW Tape Dispenser Big TD-2030", "unit"),
    ("PRINTER / BIOMETRIC / LAPTOP / TABLET", "Epson Printer TM-U220B Serial #: L9CF338018", "unit"),
    ("PRINTER / BIOMETRIC / LAPTOP / TABLET", "ZK LX50 Standalone Biometric", "unit"),
    ("PRINTER / BIOMETRIC / LAPTOP / TABLET", "Lenovo Ideapad Slim w/ Free Back Pack", "unit"),
    ("PRINTING AND WRITING PAPER", "Paper One Short Bond Paper", "ream"),
    ("PRINTING AND WRITING PAPER", "Sticker Paper Glossy A4", "pack"),
    ("PRINTING AND WRITING PAPER", "Carbon Paper Long Gold", "box"),
    ("PRINTING AND WRITING PAPER", "Photo Paper 210GSM JOJO", "pack"),
    ("PRINTING AND WRITING PAPER", "Carbon Paper Blue Long Gold", "box"),
    ("PRINTING AND WRITING PAPER", "Photo Paper 210GSM A4 JOJO", "pack"),
    ("PRINTING AND WRITING PAPER", "Hard Copy Bond Paper Long", "ream"),
    ("PRINTING AND WRITING PAPER", "Hard Copy Bond Paper Short", "ream"),
    ("PRINTING AND WRITING PAPER", "A One Bond Paper A4", "ream"),
    ("PRINTING AND WRITING PAPER", "DISR (Long Bond Paper)", "ream"),
    ("PRINTING AND WRITING PAPER", "Photopaper JOJO 180GSM", "pack"),
    ("PRINTING AND WRITING PAPER", "Photo Paper Quaff Glossy Double Sided A4 120GSM-50sheets", "pack"),
    ("PRINTING AND WRITING PAPER", "Photo Paper Quaff Glossy Double Sided A4 220GSM", "pack"),
    ("PRINTING AND WRITING PAPER", "Copy One Short Bond Paper", "ream"),
    ("PRINTING AND WRITING PAPER", "Copy One Long Bond Paper", "ream"),
    ("PRINTING AND WRITING PAPER", "Copy One Bond Paper A4", "ream"),
    ("PRINTING AND WRITING PAPER", "A4 Laminating Film 125 PRE-CUT", "pack"),
    ("PRINTER INK", "Epson 664 Magenta", "unit"),
    ("PRINTER INK", "Epson 664 Black", "unit"),
    ("PRINTER INK", "Epson Ink 003 Magenta", "unit"),
    ("PRINTER INK", "Epson Ink 003 Black", "unit"),
    ("PRINTER INK", "Epson Ink 003 Yellow", "unit"),
    ("PRINTER INK", "Epson Ink 003 Cyan", "unit"),
    ("PRINTER INK", "Canon ink 790 Yellow", "unit"),
    ("PRINTER INK", "Canon Ink 790 Black", "unit"),
    ("PRINTER INK", "Pixma 790 Ink Yellow", "unit"),
    ("PRINTER INK", "Pixma 790 Ink Magenta", "unit"),
    ("PRINTER INK", "Pixma 790 Ink Cyan", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Ballpen Matrix Black", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "HBW I GEL 0.5 Ballpen Black", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "HBW I GEL 0.5 Ballpen Blue", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Pilot Marker Black", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Pilot Marker Red", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "HBW Highlighter Pink", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "HBW Highlighter Green", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Stabilo Highlighter Pink", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Stabilo Highlighter Yellow", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Stabilo Highlighter Green", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "Whiteboard Marker Pilot Black", "unit"),
    ("PENS / MARKERS / HIGHLIGHTER", "HBW Sticky Notes 3x3", "pad"),
    ("ENVELOPES / FOLDER / CLIP", "Brown Envelop Short", "unit"),
    ("ENVELOPES / FOLDER / CLIP", "Brown Envelop Long", "unit"),
    ("ENVELOPES / FOLDER / CLIP", "Plastic Envelop Short", "unit"),
    ("ENVELOPES / FOLDER / CLIP", "Plastic Envelop Long", "unit"),
    ("ENVELOPES / FOLDER / CLIP", "Folder Short", "unit"),
    ("ENVELOPES / FOLDER / CLIP", "Folder Long", "unit"),
    ("ENVELOPES / FOLDER / CLIP", "Clip Folder Adventurer", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Pencil Mongol 2", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Vision Record Book 150 Pages", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Vision Record Book 200 Pages", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Vision Record Book 300 Pages", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Vision Record Book 500 Pages", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Clear Book Long Yellow", "unit"),
    ("PENCILS / RECORD BOOK / NOTES", "Pocket Notebook Pixels Notes", "unit"),
]
